### ISSUE TITLE
deviceModel null causing issues

### ISSUE THREAD

**Issue by acarter24** [MeltanoLabs/tap-google-analytics#154]
Just as an FYI if you are using a target which supports primary keys, I was having issues with the devices stream. The `deviceModel` field was occasionally arriving as empty string, which got converted to null, and then postgres complained.

I'm not sure why the empty string appeared rather than the `(not set)` usual placeholder, maybe there is some reprocessing on the google side.

Anyway I resolved this with an inline mapper to put the `(not set)` placeholder back if the empty string is received.

```
    config:
      start_date: 2023-03-20
      property_id: ${TAP_GA4_PROPERTY_ID}
      client_secrets: ${TAP_GOOGLE_ANALYTICS_CLIENT_SECRETS}
      key_file_location: ''
      stream_maps:
        devices:
          deviceModel: "'(not set)' if deviceModel == '' else deviceModel"
```
